[package]
name = "plat_schema"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
plat_schema_macros = { path = "../plat_schema_macros" }
